language: ruby

script: "bundle _1.17.3_ exec rake test"

before_install:
  - gem install bundler --version '1.17.3'

install: bundle _1.17.3_ install --binstubs --standalone --without documentation --path ../bundle

gemfile:
  - gemfiles/sprockets-rails_3_0.gemfile
  - gemfiles/sprockets-rails_2_3.gemfile
  - gemfiles/sprockets_3_0.gemfile
  - gemfiles/sprockets_4_0.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile

rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - 2.7
  - 3.0
  - jruby

matrix:
  allow_failures:
    - gemfile: gemfiles/rails_4_2.gemfile
      rvm: jruby
    - gemfile: gemfiles/rails_6_0.gemfile
      rvm: jruby
  exclude:
    - gemfile: gemfiles/rails_6_0.gemfile
      rvm: 2.4.6

notifications:
  email: false
