language: ruby

bundler_args: "--binstubs --standalone --without documentation --path ../bundle"

script: "bundle exec rake test"

gemfile:
  - gemfiles/sprockets_2_12.gemfile
  - gemfiles/sprockets_3_0.gemfile
  - gemfiles/sprockets_4_0.gemfile
  - gemfiles/sprockets-rails_3_0.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_0.gemfile

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1

notifications:
  email: false
